name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
            node-version: 16

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install makelove
        run: pip3 install makelove

      - name: Build App
        run: make web

      - name: Deploy to Surge
        run:  npx surge --token ${{secrets.TOKEN}} build/web garfield-organizer.surge.sh
