name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install makelove
        run: pip3 install makelove

      - name: Build App
        run: make web

      - name: Deploy to garfield-organizer.surge.sh
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'garfield-organizer.surge.sh'
          project: 'build/web'
          login: ${{ secrets.SURGE_LOGIN }}
          token: ${{ secrets.SURGE_TOKEN }}
